# Generated by Django 3.0.6 on 2020-05-29 11:56

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGOUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mob', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('contributions', models.PositiveIntegerField(default=0)),
                ('reg_num', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='contributions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
