# Generated by Django 3.0.6 on 2020-07-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='email',
            field=models.CharField(default='any', max_length=50),
        ),
        migrations.AlterField(
            model_name='queries',
            name='message',
            field=models.CharField(default='any', max_length=1000),
        ),
        migrations.AlterField(
            model_name='queries',
            name='name',
            field=models.CharField(default='any', max_length=30),
        ),
    ]
