# Generated by Django 3.0.6 on 2020-07-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_activeimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeimages',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activeimages',
            name='lat',
            field=models.FloatField(default=80.0),
        ),
        migrations.AddField(
            model_name='activeimages',
            name='lon',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='activeimages',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activeimages',
            name='url',
            field=models.URLField(default='https://www.something.com'),
        ),
    ]
