# Generated by Django 3.0.6 on 2020-07-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_auto_20200727_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
