# Generated by Django 3.0.6 on 2020-07-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_auto_20200712_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeimages',
            name='url',
        ),
        migrations.AddField(
            model_name='activeimages',
            name='name',
            field=models.CharField(default='13232', max_length=50),
        ),
    ]
