# Generated by Django 3.0.6 on 2020-07-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0005_activeimages_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='contributionImages',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
