# Generated by Django 3.0.6 on 2020-08-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0005_activearea_ngo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeimages',
            name='name',
            field=models.CharField(default='13232', max_length=100),
        ),
    ]
