# Generated by Django 3.0.6 on 2020-08-01 22:16

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0006_auto_20200801_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activearea',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='activearea',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='activeimages',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='activeimages',
            name='lon',
        ),
        migrations.AddField(
            model_name='activearea',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(23, 23), geography=True, srid=4326),
        ),
        migrations.AddField(
            model_name='activeimages',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(23, 23), geography=True, srid=4326),
        ),
    ]
