# Generated by Django 3.0.6 on 2020-07-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0006_appuser_contributionimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='contributionImages',
            field=models.CharField(blank=True, default='', max_length=100000),
        ),
    ]
