# Generated by Django 3.0.6 on 2020-07-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0007_auto_20200715_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeimages',
            name='animals',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
