# Generated by Django 3.0.6 on 2020-08-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0007_auto_20200801_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activearea',
            name='point',
        ),
        migrations.RemoveField(
            model_name='activeimages',
            name='point',
        ),
        migrations.AddField(
            model_name='activearea',
            name='lat',
            field=models.FloatField(default=80.0),
        ),
        migrations.AddField(
            model_name='activearea',
            name='lon',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='activeimages',
            name='lat',
            field=models.FloatField(default=80.0),
        ),
        migrations.AddField(
            model_name='activeimages',
            name='lon',
            field=models.FloatField(default=50.0),
        ),
    ]
