# Generated by Django 3.0.6 on 2020-07-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0008_activeimages_animals'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeimages',
            name='ngoName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usercontributionmodel',
            name='workCompleted',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
