# Generated by Django 3.0.6 on 2020-08-01 22:38

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0008_auto_20200801_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='activearea',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(78, 22), geography=True, srid=4326),
        ),
        migrations.AddField(
            model_name='activeimages',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(78, 22), geography=True, srid=4326),
        ),
    ]
