# Generated by Django 3.0.6 on 2020-07-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0009_auto_20200719_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeimages',
            name='ngoName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
