# Generated by Django 3.0.6 on 2020-07-24 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0010_auto_20200724_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=0)),
                ('lat', models.FloatField(default=80.0)),
                ('lon', models.FloatField(default=50.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('animals', models.PositiveSmallIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('ngoName', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='activeimages',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proj.ActiveArea'),
        ),
    ]
