# Generated by Django 3.0.6 on 2020-07-24 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0012_remove_activearea_animals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeimages',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proj.ActiveArea'),
        ),
    ]
