# Generated by Django 3.0.6 on 2020-07-24 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0013_auto_20200724_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeimages',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='proj.ActiveArea'),
        ),
    ]
