# Generated by Django 3.0.6 on 2020-07-26 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0017_auto_20200726_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activeimages',
            old_name='contributing_user',
            new_name='contributinguser',
        ),
    ]
